### ISSUE TITLE
Discrepancy

### ISSUE THREAD

**Issue by MainakRepositor** [gniziemazity/self-driving-car#6]
You are showing something in the video and the code works something else. This is not a good practice.

**Comment by gniziemazity** [comment]
Can you be more specific as to what is different?

**Comment by MainakRepositor** [comment]
![image](https://user-images.githubusercontent.com/64016811/207123320-5bf7bfaf-66c0-40b8-b618-8997781c6a54.png)
 

The car keeps moving in this position for more than 10 minutes

**Comment by gniziemazity** [comment]
You probably have a too small mutation amount when restarting (they all become very similar in that case).
